version: 2
jobs:
    seq2seq:
        working_directory: ~/transfromer_NN_Block
        docker:
            - image: circleci/python:3.5
        resource_class: middle
        parallelism: 4
        steps:
            - checkout
            - run: sudo pip install -r requirements.txt

    text_classfication:
        working_directory: ~/transfromer_NN_Block/transformer_text_Classfication
        resource_class: middle
        parallelism: 4
        docker:
            - image: circleci/python:3.5
        steps:
            - checkout
            - run: sudo pip install -r requirements.txt

workflows:
  version: 2
  build_and_test:
    jobs:
      - seq2seq
      - text_classfication